import tempo, { TempoText } from "@joggr/tempo";

const biography = [
  {
    title_en: "PROFILE",
    title_jp: "脇田玲 プロフィール",
    ps_en: [
      "Akira Wakita creates works that update the way we see the world by visualizing/sonifying/materializing forces that exist in front of us but cannot be perceived. His works have been exhibited at Kenninji Zen Temple, Ars Electronica Center, RedBull Music Festival, Mutek, WRO Art Center, SIGGRAPH, Kiyoharu Art Colony, Japan Media Arts Festival, Miraikan, Any Tokyo, Sapporo International Art Festival, etc. He is a professor at the Faculty of Environment and Information Studies, Keio University. Ph.D.(Media and Governance).",
    ],
    ps_jp: [
      "目の前にありながらも知覚できない力を可視化/可聴化/物質化することで、世界の見方を更新する作品をつくっている。主な展示に「龍雨図」(建仁寺 / Zen Night Walk Kyoto, 2024)、「Over Billions of Years」(モエレ沼公園 / 札幌国際芸術祭, 2024)、「アランとキースのために」(中村キース・ヘリング美術館 / Hokuto Art Program ed.1, 2022)、「脇田玲 - Photons」(清春芸術村 光の美術館, 2018)、音楽家小室哲哉との8K映像音響インスタレーション(Ars Electronica Festival, 2016)およびライブ・パフォーマンス(MUTEK/RedBull Music Festival, 2017)、「高橋コレクション『顔と抽象』-清春白樺美術館コレクションとともに」(2018)などがある。慶應義塾大学環境情報学部教授。博士（政策・メディア）。",
    ],
  },
  {
    title_en: "SOLO EXHIBITION",
    title_jp: "個展",
    ps_en: [
      "- Stream, Shibuya Stream, Tokyo, 2024",
      "- Cross Section of Light, Japan Art Bridge Gallery of Manseibashi , Tokyo, 2024",
      "- Proposal, Japan Art Bridge S4 Gallery, Tokyo, 2023",
      "- Governing Equations, Japan Art Bridge S2 Gallery, Tokyo, 2023",
      "- Photons, Museum of the Light in Kiyoharu Art Colony, Yamanashi, 2020",
      "- Scenery, Rouault Chapel in Kiyoharu Art Colony, Yamanashi, 2019",
      "- Symptom Visualized , Art & Science Galley Lab Axiom, Tokyo, 2018",
      "- Fluid, Art & Science Galley Lab Axiom, Tokyo, 2016",
    ],
    ps_jp: [
      "- Stream, 渋谷ストリーム, 渋谷, 2024",
      "- 光の断面, Japan Art Bridge Gallery of Manseibashi , 万世橋, 2024",
      "- Proposal, Japan Art Bridge S4 Gallery, 万世橋, 2023",
      "- Governing Equations, Japan Art Bridge S2 Gallery, 万世橋, 2023",
      "- Photons, 清春芸術村 光の美術館, 山梨, 2020",
      "- Scenery, 清春芸術村 ルオー礼拝堂, 山梨, 2019",
      "- Symptom Visualized - 可視化された兆候, Art & Science Galley Lab Axiom, 六本木, 2018",
      "- Fluid, Art & Science Galley Lab Axiom, 六本木, 2016",
    ],
  },

  {
    title_en: "PERFORMANCE",
    title_jp: "パフォーマンス",
    ps_en: [
      "- Live Performance collaboration between Daigoji Temple and Keio SFC supported by VIE, Osaka, 2024",
      "- MUTEK, Neuro Music - Dive into Your Brain, Tokyo, 2023",
      "- Ars Electronica Festival 2023, Future Lab Night, Linz, 2023",
      "- NxPC.Live vol.35 IAMAS x SFC, Circus Tokyo, 2019",
      "- MUTEK / RedBull Music Festival, Miraikan, Tokyo, 2017",
    ],
    ps_jp: [
      "- 醍醐寺国宝展, 醍醐寺x慶應SFC ライブパフォーマンス, 大阪中之島美術館, 大阪, 2024",
      "- MUTEK, Neuro Music - Dive into Your Brain, 渋谷, 2023",
      "- Ars Electronica Festival 2023, Future Lab Night, リンツ, 2023",
      "- NxPC.Live vol.35 IAMAS x SFC, Circus Tokyo, 2019",
      "- MUTEK / RedBull Music Festival, 日本科学未来館, お台場, 2017",
    ],
  },

  {
    title_en: "GROUP EXHIBITIONS / FESTIVALS",
    title_jp: "グループ展示 / フェスティバル",
    ps_en: [
      "- Dragon Rain, Zen Night Walk Kyoto, Kennin-ji Temple, Kyoto, 2024",
      "- Over Billions of Years, Sapporo International Art Festival, Moerenuma Park, Sapporo, 2024",
      "- Climatic Reflector, Sapporo International Art Festival, Aurora Plaza, Sapporo, 2024",
      "- Yatsugatake Art Ecology 2023, Kiyoharu Shirakaba Museum, Yamanashi, 2023",
      "- Kizugawa Art, Kyoto, 2023",
      "- Ars Electronica Festival, Data Art & Science Project, DeepSpace8K, Linz, 2023",
      "- Proposal (JR Version), Japan Art Bridge, Tokyo, 2023",
      "- Governing Equations, Japan Art Bridge, Tokyo, 2023",
      "- Cross Section of Light, Tokyo Gendai (Exhibited at Yoshii Foundation booth), Yokohama, 2023",
      "- Proposal, KOKUYO OPEN LAB., Tokyo, 2022-2023",
      "- The Universe Within, KonicaMinolta Planetaria Tokyo, 2022",
      "- Kiyoharu Jomon Exhibition, Kiyoharu Shirakaba Museum, Yamanashi, 2022",
      "- For Alan and Keith,Nakamura Keith Haring Collection, (Hokuto Art Program ed.1), Yamanashi, 2021-2022",
      "- MADD.screening, KonicaMinolta Planetaria Tokyo, 2021",
      "- Media Ambition Tokyo, Tokyo, 2021",
      "- 2020, Kiyoharu Shirakaba Museum, Yamanashi, 2021",
      "- Hokuto Art Program ed.0, Kiyoharu Art Colony, Yamanashi, 2020",
      "- Chichibugahama Art Festival, Kagawa, 2020",
      "- Hidden Superb View powered by Softbank 5G, Mixalive, Tokyo, 2020",
      "- Unbuilt Development, Tokyo, 2020",
      "- Media Ambition Tokyo, Tokyo, 2020",
      "- CLAIR DE LUNE - Akira Wakita & Isao Tomita, Global Ring Theater, Tokyo, 2020",
      "- GRADATION DAIKANYAMA, Tokyo, 2019",
      "- AnyTokyo, Tokyo, 2019",
      "- HELLO NEO SHIBUYA, Tokyo, 2019",
      "- Tokyo Midtown DESIGN TOUCH, Tokyo, 2019",
      "- Insects: Models for Design, 2121 DESIGN SIGHT, Tokyo, 2019",
      "- Roppongi Art Night, Sel Octagon Tokyo, 2019",
      "- Media Ambition Tokyo, Tokyo, 2019",
      "- School of the Future Festival - TOKYO MIDTOWN X ARS ELECTRONICA, Tokyo, 2019",
      "- ARIGATO SAKURAGAOKA Produced by Art Photo Tokyo, Shibuya, 2018",
      "- VENT,  Oya Histroy Museum, Tochigi, 2018",
      "- MUTEK,  Miraikan, Tokyo, 2018",
      "- Seia Lee Soprano Recital - Grace Note 2018, Suntory Hall, Tokyo, 2018",
      "- Ars Electronica Festival, Gallery Spaces, Linz, 2018",
      '- Scalar Field of Cosmetics, Kanebo Cosmetics "LUNASOL" 2018 Autumn Collection, Tokyo, 2018',
      "- Scalar Field of Shoes, Euglena Tokyo Headquarters, 2018",
      "- Xhiasma, Roppongi Art Night, Tokyo, 2018",
      "- Takahashi Collection - Face and Abstraction, Kiyoharu Art Colony, 2018",
      "- Media Ambition Tokyo, Tokyo, 2018",
      "- NEW SYNERGETICS, NISSAN CROSSING, Tokyo, 2017",
      "- Ars Electronica Festival, Gallery Spaces, Linz, 2017",
      "- Media Ambition Tokyo, Tokyo, 2017",
      "- ART PHOTO TOKYO -edition zero-, Tokyo, 2016",
      "- Moths, crabs, fluids, WRO Art Center at the Koszyki Hall, Warsaw, 2016",
      "- Ars Electronica Festival, Deep Space 8K, Linz, 2016",
      "- Best of Art and Science, European Forum Alpbach, Alpbach, 2016",
      "- Impetus and Movement, ARS ELECTRONICA in the KNOWLEDGE CAPITAL Vol.06, Osaka, 2016",
      "- Technarte, Bilbao, 2016",
      "- Eco Expanded City, WRO Art Center, Wrocław, 2016",
      "- Ocean General Circulation Simulation (for Geo-Prism), Miraikan, Parmanent Exhibition, Tokyo, 2016",
      "- Scalar Field of Shoes - Solo Exhibition, SPACE_XX(hiromiyoshii roppongi 2F), Tokyo, 2016",
      "- Digital Media and Japanese Graphic Design, Tokyo Midtown, 2016",
      "- SIGGRAPH Asia, Art Gallery, Kobe, 2015",
      "- Any Tokyo, Zojoji, 2015",
      "- Elements of Art and Science, Ars Electronica Center, Linz, 2015",
      "- Ars Electronica Animation Festival, Central, Linz, 2015",
      "- Amu Special Party, Tokyo, 2015",
      "- Robotinity, Ars Electronica Center, Linz, 2011-2014",
      "- Any Tokyo, Zojoji, 2014",
      "- Japan Media Arts Festival Kushiro Exhibition, Kushiro, 2014",
      "- Techfest 2012, invited work of Japan Media Arts Festival, IIT Mumbai, 2012",
      "- ACE 2011, Interactive Art, Gold Award, Lisbon, 2011",
      "- SIGGRAPH ASIA 2011, Emerging Technologies, Hongkong, 2011",
      "- Japan Media Arts Festival Exhibition, The National Art Center, Tokyo, 2010",
      "- INTERIOR LIFESTYLE TOKYO, 2009",
      "- Interactive Tokyo, 2006",
      "- SIGGRAPH 2006, Emerging Technologies, Boston, 2006",
      "- SIGGRAPH 2005, Cyberfashion Show, Los Angeles, 2005",
      "- Japan Media Arts Festival, Tokyo, 2001",
      "- Graz Biennial on Media + Architecture, Graz, 2001",
      "- cast01, Bonn, 2001",
      "- Architecture Media Player, Traveling exhibition, Italia, 2000",
      "- Electronic Language International Festival, invited, Sao Paulo, 2000",
      "- European Media Art Festival, Osnabrueck, 2000",
    ],
    ps_jp: [
      "- 龍雨図, Zen Night Walk Kyoto, 建仁寺, 2024",
      "- Over Billions of Years, 札幌国際芸術祭, モエレ沼公園 SPACE 1, 札幌, 2024",
      "- Climatic Reflector, 札幌国際芸術祭, オーロラプラザ, 札幌, 2024",
      "- 山梨国際芸術祭 八ヶ岳アート・エコロジー, 清春白樺美術館 第二展示室 清春芸術村, 山梨, 2023",
      "- 木津川アート, きっづ光科学館ふぉとん, 京都, 2023",
      "- Ars Electronica Festival, Data Art & Science Project, DeepSpace8K, リンツ, 2023",
      "- Proposal (JR Version), Japan Art Bridge, 万世橋, 2023",
      "- Governing Equations, Japan Art Bridge, 万世橋, 2023",
      "- Cross Section of Light, 東京現代（吉井財団ブースにて展示）, パシフィコ横浜, 2023",
      "- Proposal, KOKUYO OPEN LAB., 品川, 2022-2023",
      "- 内なる宇宙, コニカミノルタ プラネタリア東京, 2022",
      "- 清春縄文展, 清春白樺美術館, 山梨, 2022",
      "- アランとキースのために, 中村キース・ヘリング美術館, (Hokuto Art Program ed.1), 山梨, 2021-2022",
      "- MADD.screening, コニカミノルタ プラネタリア東京, 2021",
      "- Media Ambition Tokyo, 東京シティビュー, 2021",
      "- 2020, 清春白樺美術館, 山梨, 2021",
      "- Hokuto Art Program ed.0, 清春芸術村, 山梨, 2020",
      "- 父母ヶ浜芸術祭, 香川, 2020",
      "- Hidden Superb View powered by Softbank 5G, Mixalive TOKYO, 池袋, 2020",
      "- つくらない都市計画, kudan house, 東京, 2020",
      "- メディア・アンビション・トウキョウ, 渋谷QWS, 2020",
      "- CLAIR DE LUNE - Akira Wakita & Isao Tomita, Global Ring Theater, 池袋, 2020",
      "- GRADATION 代官山, 東京, 2019",
      "- AnyTokyo, 九段下, 2019",
      "- HELLO NEO SHIBUYA, 渋谷, 2019",
      "- Tokyo Midtown DESIGN TOUCH, 六本木, 2019",
      "- 虫展 : デザインのお手本, 2121 DESIGN SIGHT, 六本木, 2019",
      "- 六本木アートナイト, Sel Octagon Tokyo, 六本木, 2019",
      "- メディア・アンビション・トウキョウ, 六本木, 2019",
      "- 未来の学校祭 - TOKYO MIDTOWN X ARS ELECTRONICA, Tokyo, 2019",
      "- ARIGATO SAKURAGAOKA Produced by Art Photo Tokyo, 渋谷, 2018",
      "- VENT,  大谷資料館, 栃木, 2018",
      "- MUTEK,  日本科学未来館, お台場, 2018",
      "- Seia Lee Soprano Recital - Grace Note 2018, サントリーホール, 東京, 2018",
      "- アルス・エレクトロニカ・フェスティバル, Gallery Spaces, リンツ, 2018",
      "- Scalar Field of Cosmetics, カネボウ化粧品「LUNASOL」2018 AUTUMN COLLECTION, 2018",
      "- Scalar Field of Shoes, ユーグレナ 東京本社ビル, 2018",
      "- Xhiasma, 六本木アートナイト, 2018",
      "- 高橋コレクション - 顔と抽象, 清春芸術村, 2018",
      "- メディア・アンビション・トウキョウ, 六本木, 2018",
      "- NEW SYNERGETICS, NISSAN CROSSING, 銀座, 2017",
      "- Ars Electronica Festival, Gallery Spaces, リンツ, 2017",
      "- メディア・アンビション・トウキョウ, 六本木, 2017",
      "- ART PHOTO TOKYO -edition zero-, 茅場町, 2016",
      "- Moths, crabs, fluids, WRO Art Center at the Koszyki Hall, ワルシャワ, 2016",
      "- Ars Electronica Festival, Deep Space 8K, リンツ, 2016",
      "- Best of Art and Science, European Forum Alpbach, アルプバッハ, 2016",
      "- チカラとウゴキ, ARS ELECTRONICA in the KNOWLEDGE CAPITAL Vol.06, 大阪, 2016",
      "- Technarte, ビルバオ, 2016",
      "- Eco Expanded City, WROアートセンター, ブロツワフ, 2016",
      "- Geo-Prism 海洋大循環シミュレーション, 日本科学未来館, 常設展示, 2016",
      "- Scalar Field of Shoes 展, SPACE_XX(hiromiyoshii roppongi 2F), 六本木, 2016",
      "- デジタルメディアと日本のグラフィックデザイン, 東京ミッドタウン, 2016",
      "- SIGGRAPH Asia, Art Gallery, 神戸, 2015",
      "- Any Tokyo, 増上寺, 2015",
      "- Elements of Art and Science, アルス・エレクトロニカ・センター, リンツ, 2015",
      "- Ars Electronica Animation Festival, Central, リンツ, 2015",
      "- Amu Special Party, 恵比寿AMU, 2015",
      "- Robotinity, アルス・エレクトロニカ・センター, リンツ, 2011-2014",
      "- Any Tokyo, 増上寺, 2014",
      "- 文化庁メディア芸術祭 釧路展, 北海道立釧路芸術館, 2014",
      "- Techfest 2012, 文化庁メディア芸術祭の招待作品として出展, ムンバイ, 2012",
      "- ACE 2011, Interactive Art, Gold Award, リスボン, 2011",
      "- SIGGRAPH ASIA 2011, Emerging Technologies, 香港, 2011",
      "- 文化庁メディア芸術祭, 国立新美術館, 2010",
      "- INTERIOR LIFESTYLE TOKYO, 2009",
      "- インタラクティブ東京, 日本科学未来館, 2006",
      "- SIGGRAPH 2006, Emerging Technologies, ボストン, 2006",
      "- SIGGRAPH 2005, Cyberfashion Show,　ロスアンゼルス, 2005",
      "- 文化庁メディア芸術祭, 2001",
      "- Graz Biennial on Media + Architecture, グラーツ, 2001",
      "- cast01, ボン, 2001",
      "- Architecture Media Player, Traveling exhibition, イタリア, 2000",
      "- Electronic Language International Festival, 招待出展, サンパウロ, 2000",
      "- European Media Art Festival, オスナブリュック, 2000",
    ],
  },

  /*
  {
    title_en: 'AWARDS',
    title_jp: '主な受賞歴',
    ps_en: [
      '- Asia Digital Art Award, Interactive Art Category, Finalist, 2012',
      '- CAADRIA, Best Paper Award, New Castle, 2011.',
      '- Advances in Computer Entertainment Technology, Interactive Art, Gold Award, 2011.',
      '- Asia Digital Art Award, Interactive Art Category, Finalist, 2011',
      "- Japan Media Arts Festival, Jury's Selection, 2010",
      '- Asia Digital Art Award, Digital Design Category, Excellent Award, 2003',
      "- Japan Media Arts Festival, Jury's Selection, 2001",
      '- Web3D RoundUP Golden Rosso Award, Technology Award, 2000',
      '- Multimedia Grand Prix 2000, Network Division, Information Design Award, 2000',
      '- Nikkei Architecture Digital Design Competition, Grand Prix, 1999',
    ],
    ps_jp: [
      '- アジアデジタルアート大賞, インタラクティブアート部門 入賞, 2012',
      '- CAADRIA, Best Paper Award 受賞, ニューカッスル, 2011.',
      '- Advances in Computer Entertainment Technology, Interactive Art 部門, Gold Award 受賞, 2011.',
      '- アジアデジタルアート大賞, インタラクティブアート部門 入賞, 2011',
      '- 文化庁メディア芸術祭, 審査委員推薦作品, 2010',
      '- アジアデジタルアート大賞, デジタルデザイン部門 優秀賞, 2003',
      '- 文化庁メディア芸術祭, 審査委員推薦作品, 2001',
      '- Web3D RoundUP Golden Rosso Award, Technology Award, 2000',
      '- マルチメディアグランプリ, ネットワーク部門 情報デザイン賞, 2000',
      '- 日経アーキテクチュア第5回デジタルデザインコンペ, 最優秀賞, 1999',
    ],
  },
  */

  {
    title_en: "BOOKS",
    title_jp: "主な著書",
    ps_en: [
      "- Entrance Examination Issues for the Year 2050, Nihon Keizai Shimbun Publishing, 2022",
      "- Access to Materials - Material Computing for Design, Art and Architecture, BNN, 2013",
      "- x-DESIGN, Keio University Press, 2013",
    ],
    ps_jp: [
      "- 2050年の入試問題, 日本経済新聞出版, 2022",
      "- Access to Materials - デザイン/アート/建築のためのマテリアルコンピューティング入門, BNN新社, 2013",
      "- x-DESIGN - 未来をプロトタイピングするために, 慶應義塾大学出版会, 2013",
    ],
  },

  {
    title_en: "CONTACT",
    title_jp: "コンタクト",
    ps_en: [
      "Request for works and interviews, please email to the address below. ",
      "a(dot)wakita(at)gmail(dot)com",
    ],
    ps_jp: [
      "作品やインタビューのご依頼は下記にご連絡をお願いいたします。\ba(dot)wakita(at)gmail(dot)com",
    ],
  },
];

let markdown = tempo();
for (const item of biography) {
  markdown.h2(item.title_jp);
  markdown.paragraph(item.ps_jp.join("\n"));
}

const file = Bun.file("./src/pages/biography.md");
await Bun.write(file, markdown.toString());
